/*
* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package axisbank;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Date.*;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author kg223
 */
public class Accountsss extends javax.swing.JInternalFrame {

    private byte[] imageBytes;
	private Image image;

	/**
     * Creates new form Customer
     */
   
    public Accountsss() {
        initComponents();
       autoID();
       branch();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(new Color(173, 216, 230));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(65, 38, 155, 39);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(63, 124, 176, 39);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(63, 193, 176, 39);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setBounds(63, 270, 176, 30);
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setBounds(63, 332, 176, 39);
        txtcust = new javax.swing.JTextField();
        txtcust.setFont(new Font("Tahoma", Font.BOLD, 16));
        txtcust.setBounds(290, 122, 166, 41);
        txtlname = new javax.swing.JTextField();
        txtlname.setFont(new Font("Tahoma", Font.BOLD, 16));
        txtlname.setBounds(290, 192, 166, 40);
        txtbal = new javax.swing.JTextField();
        txtbal.setFont(new Font("Tahoma", Font.BOLD, 16));
        txtbal.setBounds(290, 332, 166, 39);
        jButton1 = new javax.swing.JButton();
        jButton1.setBounds(310, 426, 110, 56);
        jButton2 = new javax.swing.JButton();
        jButton2.setBounds(449, 426, 126, 56);
        jLabel17 = new javax.swing.JLabel();
        jLabel17.setBounds(290, 38, 81, 39);
        txtaccount = new javax.swing.JComboBox();
        txtaccount.setFont(new Font("Tahoma", Font.BOLD, 16));
        txtaccount.setBounds(290, 269, 166, 31);
        jButton3 = new javax.swing.JButton();
        jButton3.setBounds(165, 426, 110, 56);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel2.setText("Account No");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setText("customer id");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel4.setText("customer name");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel5.setText("account type");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel6.setText("balance");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtcust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcustKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Add");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Cancel");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 204));
        jLabel17.setText("jLabel17");
        jLabel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel17.setOpaque(true);

        txtaccount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ", "Saving", "Current", "Fix" }));

        jButton3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Find");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        
        JLabel lblNewLabel = new JLabel("");
        lblNewLabel.setBackground(new Color(173, 216, 230));
        lblNewLabel.setBounds(0, 0, 980, 766);
        lblNewLabel.setIcon(new ImageIcon("C:\\Users\\AMON HCV\\Desktop\\banner-glance.jpg"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        			.addGap(114))
        );
        jPanel1.setLayout(null);
        jPanel1.add(jLabel2);
        jPanel1.add(jLabel6);
        jPanel1.add(jLabel5);
        jPanel1.add(jLabel4);
        jPanel1.add(jLabel3);
        jPanel1.add(txtcust);
        jPanel1.add(txtlname);
        jPanel1.add(txtbal);
        jPanel1.add(jLabel17);
        jPanel1.add(txtaccount);
        jPanel1.add(jButton3);
        jPanel1.add(jButton1);
        jPanel1.add(jButton2);
        
        label = new JLabel("");
        label.setBounds(543, 38, 415, 320);
        jPanel1.add(label);
        jPanel1.add(lblNewLabel);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
        	 autoID();
        	String account_no = jLabel17.getText();
            String customerid = txtcust.getText();
            String custname = txtlname.getText();
            String acctype = txtaccount.getSelectedItem().toString();
             String bal = txtbal.getText();
            //String state = txtstate.getText();
            //String city = txtbal.getText();
            //String phone = txtphone.getText();
            //Date dob = jDate.getDate();
            //String pan = txtpan.getText();
            //String adhar = txtadhar.getText();
            //String email = txtemail.getText();
            //String seq_a = txtseq.getText();
            //String branchcode = txtbrnchcode.getText();
            //String branch = jComboBox1.getSelectedItem().toString();
            //String seq_q = jCombo.getSelectedItem().toString();
            
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/axisbanks?serverTimezone=UTC","root","");
            insert = conn.prepareStatement("insert into account(acc_id,cust_id,acc_type,balance)"+"values(?,?,?,?)");
            insert.setString(1,account_no);
            insert.setString(2,customerid);
            insert.setString(3,acctype);
            insert.setString(4,bal);
            //insert.setString(5,state);
            //insert.setString(6,city);
            //insert.setString(7,phone);
            //insert.setString(8,pan);
            //insert.setString(9,adhar);
            //insert.setString(10,email);
            //insert.setString(11,branchcode);
            //insert.setString(12,branch);
           // insert.setString(13,seq_q);
            //insert.setString(14,seq_a);
            //insert.setDate(15, (java.sql.Date) dob);
            insert.execute();
            
           
          
            JOptionPane.showMessageDialog(this,"Account Created");
           
            txtcust.setText("");
            txtlname.setText("");
            txtbal.setText("");          
            txtaccount.setSelectedIndex(-1);
           
            txtcust.requestFocus();
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Accountsss.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Accountsss.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
               
               setVisible(false);
               dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            String cust_id = txtcust.getText();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/axisbanks?serverTimezone=UTC","root","");
            insert = conn.prepareStatement("select * from customer where cust_id = ?");
            insert.setString(1,cust_id);
            rs = insert.executeQuery();
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(this,"Customer No. not found");
            }
            else
            {
                String firstname = rs.getString("firstname");
                imageBytes = rs.getBytes("image");
                image = getToolkit().createImage(imageBytes);
                ImageIcon icon = new ImageIcon(image);
                label.setIcon(icon);
                txtlname.setText(firstname.trim());
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Accountsss.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Accountsss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtcustKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        
        
        try {
            // TODO add your handling code here:
            String procod = txtcust.getText();
            
            Class.forName("com.mysql.cj.dbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/customer","root","");
            insert = conn.prepareStatement("select * from customer where cust_id = ?");
            insert.setString(1,procod);
            rs = insert.executeQuery();
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(this,"Customer No. not found");
            }
            else
            {
                String firstname = rs.getString("firstname");
                txtlname.setText(firstname.trim());
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Accountsss.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Accountsss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtcustKeyPressed
       

        
    Connection conn;
    PreparedStatement insert;
    ResultSet rs;
   
        public void autoID()
        {
            try
            {
                
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    conn = DriverManager.getConnection("jdbc:mysql://localhost/axisbanks?serverTimezone=UTC","root","");
                    Statement s = (Statement)conn.createStatement();
                    //JOptionPane.showMessageDialog(null,"Connected");
                    ResultSet rs = s.executeQuery("select MAX(acc_id) from account");
                    rs.next();
                    rs.getString("MAX(acc_id)");
                    
                    if(rs.getString("MAX(acc_id)")==null)
                    {
                        jLabel17.setText("A001");
                    }
                    else
                    {
                        long id = Long.parseLong(rs.getString("MAX(acc_id)").substring(2,rs.getString("MAX(acc_id)").length()));
                        id++;
                        
                        jLabel17.setText("A" + String.format("%03d" ,id));
                    }
                    
                   
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Accountsss.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Accountsss.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
    
    public void branch() 
    {
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/axisbanks?serverTimezone=UTC","root","");
            insert = conn.prepareStatement("select * from branch");
            ResultSet rs = insert.executeQuery();
            //jComboBox1.removeAllItems();
            while(rs.next())
            {
                //jComboBox1.addItem(rs.getString(2));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Accountsss.class.getName()).log(Level.SEVERE, null, ex);
        }catch(SQLException ex)
        {
            Logger.getLogger(Accountsss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox txtaccount;
    private javax.swing.JTextField txtbal;
    private javax.swing.JTextField txtcust;
    private javax.swing.JTextField txtlname;
    private JLabel label;
    // End of variables declaration//GEN-END:variables

    private void exit() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
