/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package axisbank;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author kg223
 */
public class transfer extends javax.swing.JInternalFrame {

    /**
     * Creates new form transfer
     */
    public transfer() {
    	getContentPane().setBackground(new Color(175, 238, 238));
        initComponents();
        
        
    }
    Connection conn1;
        PreparedStatement pst;
        PreparedStatement pst1;
        PreparedStatement pst2;
        PreparedStatement pst3;
        ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton2 = new javax.swing.JButton();
        jButton2.setFont(new Font("Tahoma", Font.BOLD, 20));
        jButton3 = new javax.swing.JButton();
        jButton3.setFont(new Font("Tahoma", Font.BOLD, 20));

        jButton2.setText("Transfer");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton1 = new javax.swing.JButton();
        
                jButton1.setFont(new Font("Arial Black", Font.BOLD, 20)); // NOI18N
                jButton1.setText("Find");
                jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });
        txtfacc = new javax.swing.JTextField();
        txtfacc.setFont(new Font("Arial Black", Font.BOLD, 20));
        jLabel1 = new javax.swing.JLabel();
        
                jLabel1.setFont(new Font("Arial Black", Font.BOLD, 20)); // NOI18N
                jLabel1.setText("From Account");
                jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtbal = new javax.swing.JTextField();
        txtbal.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyTyped(KeyEvent arg0) {
        		
        		if(!(Character.isDigit(arg0.getKeyChar())))
        		{
        			arg0.consume();
        		}if(txtbal.getText().length() >=7)
        		{
        			arg0.consume();
        		}
        	}
        });
        txtbal.setFont(new Font("Arial Black", Font.BOLD, 20));
        jLabel2 = new javax.swing.JLabel();
        
                jLabel2.setFont(new Font("Arial Black", Font.BOLD, 20)); // NOI18N
                jLabel2.setText("Balance");
                jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txttoacc = new javax.swing.JTextField();
        txttoacc.setFont(new Font("Arial Black", Font.BOLD, 20));
        jLabel3 = new javax.swing.JLabel();
        
                jLabel3.setFont(new Font("Arial Black", Font.BOLD, 20)); // NOI18N
                jLabel3.setText("To Account");
                jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4 = new javax.swing.JLabel();
        
                jLabel4.setFont(new Font("Arial Black", Font.BOLD, 20)); // NOI18N
                jLabel4.setText("Amount");
                jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtamount = new javax.swing.JTextField();
        txtamount.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyTyped(KeyEvent e) {
        		
        		if(!(Character.isDigit(e.getKeyChar())))
        		{
        			e.consume();
        		}if(txtamount.getText().length() >=7)
        		{
        			e.consume();
        		}
        	}
        });
        txtamount.setFont(new Font("Arial Black", Font.BOLD, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(59)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(55)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        								.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))))
        					.addGap(49)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(txtbal, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        						.addComponent(txtfacc, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        						.addComponent(txttoacc, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        						.addComponent(txtamount, Alignment.TRAILING, 201, 201, Short.MAX_VALUE))))
        			.addGap(90)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jButton3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jButton2, GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
        			.addGap(258))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(91)
        					.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(94)
        					.addComponent(txtfacc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jButton1)
        			.addPreferredGap(ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel2)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(txtbal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(57)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel3)
        						.addComponent(txttoacc, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
        					.addGap(46)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(txtamount, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        					.addGap(306))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(34)
        					.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try {
            // TODO add your handling code here:
            String procod = txtfacc.getText();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn1 = DriverManager.getConnection("jdbc:mysql://localhost/axisbanks?serverTimezone=UTC","root","");
            pst = conn1.prepareStatement("Select a.balance from customer c,account a where c.cust_id = a.cust_id and a.acc_id =?");
            pst.setString(1,procod);
            rs = pst.executeQuery();
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(this,"Account ID not found");
            }
            else
            {
                String bal = rs.getString(1);
                txtbal.setText(bal.trim());
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Accountsss.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Accountsss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String facc = txtfacc.getText();
        String bal= txtbal.getText();
        String toaccount = txttoacc.getText();
        String amoun = txtamount.getText();
        Integer amount=Integer.parseInt(amoun);
        try
        {
            
        
        	Class.forName("com.mysql.cj.jdbc.Driver");
            conn1 = DriverManager.getConnection("jdbc:mysql://localhost/axisbanks?serverTimezone=UTC","root","");
            System.out.print(amount);
            System.out.print(facc);
            //conn1.setAutoCommit(false);
            pst1 = conn1.prepareStatement("update account set balance = balance - ? where acc_id=?");
         
        	  
         
            pst1.setInt(1,amount);
           pst1.setString(2,facc);
           pst1.execute();
            System.out.print(amount);
           System.out.print(toaccount);  
            pst2 = conn1.prepareStatement("update account set balance = balance + ? where acc_id=?");
            pst2.setInt(1,amount);
           pst2.setString(2,toaccount);
           pst2.execute();
           
           pst3 = conn1.prepareStatement("insert into transfer(f_account,t_account,amount) values(?,?,?)");
           pst3.setString(1,facc);
            pst3.setString(2,toaccount);
            pst3.setInt(3,amount);   
            pst3.execute();
            JOptionPane.showMessageDialog(this,"Amount Transfered......");
            setVisible(false);
            dispose();
           
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(transfer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            try {
                Logger.getLogger(transfer.class.getName()).log(Level.SEVERE, null, ex);
                conn1.rollback();
            } catch (SQLException ex1) {
                Logger.getLogger(transfer.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtbal;
    private javax.swing.JTextField txtfacc;
    private javax.swing.JTextField txttoacc;
    // End of variables declaration//GEN-END:variables
}
