/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package axisbank;

import java.sql.Connection;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author kg223
 */
public class Withdraw extends javax.swing.JInternalFrame {

    /**
     * Creates new form Deposit
     */
    public Withdraw() {
    	getContentPane().setBackground(new Color(175, 238, 238));
        initComponents();
        date();
    }
    Connection conn;
    PreparedStatement insert;
    PreparedStatement update;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setForeground(Color.BLUE);
        jLabel2.setFont(new Font("Tahoma", Font.BOLD, 20));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setForeground(Color.BLUE);
        jLabel3.setFont(new Font("Tahoma", Font.BOLD, 20));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setForeground(Color.BLUE);
        jLabel4.setFont(new Font("Tahoma", Font.BOLD, 20));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setForeground(Color.RED);
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setForeground(Color.RED);
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setForeground(Color.RED);
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setForeground(Color.BLUE);
        jLabel10.setFont(new Font("Tahoma", Font.BOLD, 20));
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setForeground(Color.RED);
        jLabel12 = new javax.swing.JLabel();
        jLabel12.setForeground(Color.RED);
        txtamount = new javax.swing.JTextField();
        txtamount.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyTyped(KeyEvent e) {
        		
        		if(!(Character.isDigit(e.getKeyChar())))
        		{
        			e.consume();
        		}if(txtamount.getText().length() >=7)
        		{
        			e.consume();
        		}
        	}
        });
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Tahoma", Font.BOLD, 18));
        jLabel9 = new javax.swing.JLabel();

        jLabel2.setText("Customer No");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Firstname");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Lastname");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new Font("Arial", Font.BOLD, 30)); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new Font("Arial", Font.BOLD, 30)); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new Font("Arial", Font.BOLD, 30)); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("Balance");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new Font("Arial Black", Font.BOLD, 28)); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new Font("Lucida Bright", Font.BOLD, 26)); // NOI18N
        jLabel12.setText("Withdraw");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtamount.setBackground(new java.awt.Color(97, 34, 34));
        txtamount.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton1.setText("OK");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Date");

        jLabel9.setFont(new Font("Arial", Font.BOLD, 22)); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setForeground(Color.BLUE);
        
                jLabel1.setFont(new Font("Eras Bold ITC", Font.BOLD, 30)); // NOI18N
                jLabel1.setText("Enter Account No");
                jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtacc = new javax.swing.JTextField();
        txtacc.setFont(new Font("Tahoma", Font.BOLD, 16));
        jButton3 = new javax.swing.JButton();
        
                jButton3.setFont(new Font("Arial Black", Font.BOLD, 20)); // NOI18N
                jButton3.setText("Find");
                jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton3ActionPerformed(evt);
                    }
                });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(175)
        					.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        					.addGap(27)
        					.addComponent(jLabel9))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(118)
        							.addComponent(jLabel1))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(56)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        							.addGap(49)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        								.addComponent(jButton3, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE))))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(59)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(txtamount, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(37)
        							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE)
        							.addGap(39)
        							.addComponent(jButton2))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(121)
        							.addComponent(jLabel11))))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(131)
        					.addComponent(txtacc, GroupLayout.PREFERRED_SIZE, 267, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(331, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(563, Short.MAX_VALUE)
        			.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
        			.addGap(368))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(14)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel9)
        						.addComponent(jLabel5))
        					.addGap(36)
        					.addComponent(jLabel1))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(45)
        					.addComponent(jLabel10)
        					.addGap(18)
        					.addComponent(jLabel11)))
        			.addGap(12)
        			.addComponent(txtacc, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(34)
        					.addComponent(jLabel12))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jButton3)))
        			.addGap(1)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(34)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel6)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(31)
        					.addComponent(txtamount, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)))
        			.addGap(40)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel7)))
        			.addGap(19)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8)
        				.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(208, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void date()
        {
            DateTimeFormatter dtd = DateTimeFormatter.ofPattern("dd/MM/YYYY");
            LocalDateTime now = LocalDateTime.now();
            String date = dtd.format(now);
            
            jLabel9.setText(date);
        }
    
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            
            String accno = txtacc.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/axisbanks?serverTimezone=UTC","root","");
            
            insert = conn.prepareStatement("Select c.cust_id,c.firstname,c.lastname,a.balance from customer c, account a where c.cust_id = a.cust_id and a.acc_id =?");
            insert.setString(1,accno);
            rs = insert.executeQuery();
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(this,"Account not Found");
            }
            else
            {
                String id = rs.getString(1);
                String firstname = rs.getString(2);
                String lastname = rs.getString(3);
                String balance = rs.getString(4);
                
                
                jLabel6.setText(id.trim());
                jLabel7.setText(firstname.trim());
                jLabel8.setText(lastname.trim());
                jLabel11.setText(balance.trim());
                
                
                
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            conn.setAutoCommit(false);
            String accno = txtacc.getText();
            String cust_id = jLabel6.getText();
            String firstname = jLabel7.getText();
            String lastname = jLabel8.getText();
            String date = jLabel9.getText();
             String balanc = jLabel11.getText();
            Integer balance=Integer.parseInt(balanc);
            String amoun = txtamount.getText();
            Integer amount=Integer.parseInt(amoun);
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/axisbanks?serverTimezone=UTC","root","");
            
             insert = conn.prepareStatement("insert into withdraw(acc_id,cust_id,date,balance,withdraw)values(?,?,?,?,?)");
         //    System.out.print(amount);
             	if(amount<=balance)
             	{
             		
             	
             insert.setString(1,accno);
             insert.setString(2,cust_id);
             insert.setString(3,date);
             insert.setInt(4,balance);
             insert.setInt(5,amount);
             insert.execute();
             
             PreparedStatement insert1 = conn.prepareStatement("update deposit set balance = balance+ ? where acc_id = ?");
             insert1.setInt(1,amount);
            insert1.setString(2,accno);
            insert1.execute();
           // insert.setString(2,cust_id);
            //insert.setString(3,date);
            
           // insert.setInt(5,amount);
            
            
            
             System.out.print(amount);
             update = conn.prepareStatement("update account set balance = balance- ? where acc_id = ?");
             update.setInt(1,amount);
             update.setString(2,accno);
             update.execute();
            JOptionPane.showMessageDialog(this,"Withdraw......");
            setVisible(false);
            dispose();
            
             	}
             	else
             	{
             		JOptionPane.showMessageDialog(null, "INSUFFICIENT AMOUNT");
             	}
            
             
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            
            try {
                Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
                conn.rollback();
            } catch (SQLException ex1) {
                Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtacc;
    private javax.swing.JTextField txtamount;
    // End of variables declaration//GEN-END:variables
}
